apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: chip-high-cpu
  namespace: chip
spec:
  scaleTargetRef:
    name: chip
  minReplicaCount: 3
  maxReplicaCount: 10
  pollingInterval: 10  
  cooldownPeriod:  20
  advanced:
    horizontalPodAutoscalerConfig:
      behavior:
        scaleDown:
          stabilizationWindowSeconds: 60
        scaleUp:
          stabilizationWindowSeconds: 20          
  triggers: # see https://keda.sh/docs/2.13/scalers/cpu/#trigger-specification
  - type: cpu
    metricType: Utilization # 'Utilization' or 'AverageValue'
    metadata:
      value: "20" # percentage
