# https://keda.sh/docs/2.14/concepts/authentication/#re-use-credentials-and-delegate-auth-with-triggerauthentication

apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: nutrition-aws-credentials
  namespace: nutrition
spec:
  podIdentity:
    provider: aws

---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: health-data-offload-sqs
  namespace: nutrition
spec:
  scaleTargetRef:
    name: health-data-offload
  minReplicaCount: 1
  maxReplicaCount: 30
  pollingInterval: 10  
  cooldownPeriod:  30
  advanced:
    horizontalPodAutoscalerConfig:
      behavior:
        scaleDown:
          stabilizationWindowSeconds: 60
        scaleUp:
          stabilizationWindowSeconds: 60          
  triggers:
  - type: aws-sqs-queue
    authenticationRef:
      name: nutrition-aws-credentials  
    metadata:
      queueURL: "your_sqs_queue_url"
      awsRegion: "us-east-1"
      queueLength: "20"  # Number of messages per pod
