---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: chip-green
  namespace: chip
spec:
  hosts:
  - "chip-green.chip.svc.cluster.local"
  - "chip-green.yourdomain.com"
  gateways:
  - chip
  http:
  - route:
    - destination:
        host: chip-green
        port:
          number: 8080 
    retries:
      attempts: 3
      perTryTimeout: 10500ms
      retryOn: 5xx

---
apiVersion: v1
kind: Service
metadata:
  name: chip-green
  namespace: chip 
  labels:
    app.kubernetes.io/name: chip
    app.kubernetes.io/instance: chip 
spec:
  ports:
  - name: web
    port: 8080
    protocol: TCP
  selector:
    app: chip
  type: ClusterIP

---
apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: chip-warm-up-operation
  namespace: chip
spec:
  metrics:
  - name: k6-stack-warm-up
    failureLimit: 0
    provider:
      job:
        spec:
          backoffLimit: 1
          template:
            metadata:
              labels:
                istio-injection: disabled
                sidecar.istio.io/inject: "false"
            spec:
              containers:
              - name: k6-stack-warm-up
                image: fidelissauro/chip-test-green:latest
              restartPolicy: Never

---
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  labels:
    app: chip
  name: chip
  namespace: chip
spec:
  revisionHistoryLimit: 3
  strategy:
    blueGreen: 
      activeService: chip
      previewService: chip-green
      autoPromotionEnabled: true
      prePromotionAnalysis:
        templates:
        - templateName: chip-warm-up-operation
  replicas: 5
  selector:
    matchLabels:
      app: chip
  template:
    metadata:       
      labels:
        app: chip
        name: chip
        version: v9
    spec:
      topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: "topology.kubernetes.io/zone"
        whenUnsatisfiable: ScheduleAnyway
        labelSelector:
          matchLabels:
            app: chip
          
      nodeSelector:
        karpenter.sh/nodepool: chip-capacity

      containers:
      - name: chip
        image: fidelissauro/chip:v1
        ports:
        - containerPort: 8080
          name: http
        resources:
          requests:
            cpu: 250m
            memory: 512Mi
          limits:
            cpu: 250m
            memory: 512Mi            
        startupProbe:
          failureThreshold: 10
          httpGet:
            path: /readiness
            port: 8080
          periodSeconds: 10
        livenessProbe:
          failureThreshold: 10
          httpGet:
            httpHeaders:
            - name: Custom-Header
              value: Awesome
            path: /liveness
            port: 8080
          periodSeconds: 10
        env:
        - name: CHAOS_MONKEY_ENABLED
          value: "false"  
        - name: CHAOS_MONKEY_MODE
          value: "critical" 
        - name: CHAOS_MONKEY_LATENCY
          value: "true"            
        - name: CHAOS_MONKEY_EXCEPTION
          value: "true"   
        - name: CHAOS_MONKEY_APP_KILLER
          value: "true"   
        - name: CHAOS_MONKEY_MEMORY
          value: "true"    
        - name: VERSION
          value: "v9"                                              
      terminationGracePeriodSeconds: 60
